print("my name is lidia")
print("i am pretty cool and i like strawberries")
print("i am half finnish and half PERSIAN")
print("i have two older sisters")
their_name = input("whats your name???")
print(f"hey {their_name},whats up")