print("hello")
name = input("what is your name? ")
print("             ")
print(f"hello {name}, this is a murder mystery.")
print(" when typing is yes or no answers, type yes or no all lowercase but if it is not a yes or no question type it exactly how it is shown to you. if there is an place where you could write but theres no question, there is just input there so there is a pause in the writing. it is for the dramatics so not everything is shown to you at once")
print("------------------------------------------------------------------------")
print("   ")
print("while you are walking your dog Scoot outside, you look into your mailbox when you are walking back into your house.")
print("there is a red envelope")
print("you grab it")
print("there is an invite")
will_u_go = input("You are invited to a fancy party in an old mansion. Will you go? yes or no:  ")
if will_u_go == "yes":
    plus1 = input("who will you take as your plus one? Miss Peacoat, Mr. Sharply, or Nessy Lock?   ")
    if plus1 == "Miss Peacoat":
        print("she arrives at your door with a long pea colored coat")
        print("you greet one another and drive in your car to the mansion.")
        print("when you arrive, it starts raining a lot. You both run from the car to the mansion and ring the doorbell.")
        print("right away, the butler opened the door.")
        print(f" ''hello and welcome, {name} and Miss Peacoat'' the butler said. ")
        print(" ''my name is Guntar'' the butler, Guntar said. ")
        print(" ''please, let me take your jackets,'' he said")
        print("you and miss peacoat hand over your soaking wet jackets. they got so wet from the time you ran from the car to the door. You and miss peacoat stepped into the warm and fancy mansion.")
        print(" ''this is a very nice place you have,'' you said.")
        print(f" ''why thank you, {name}, not mine though,'' Guntar called over his shoulder while he led you and miss peacoat to the main room. ")
        eztra = input(" at the same time, the doorbell rings, and Guntar the butler opens the door again.")
        print("The door opens to reveal Mr. Sharply, Miss Peacoat, Charles William the senator, and Zepper.")
        print("''why is Zepper here?'' Miss Peacoat whispers in your ear. Zepper is known for doing a bunch of shady things.")
        print("You, Nessy Lock, Mr. Sharply, Charles, Zepper, and Miss Peacoat all walked into the dining room at Guntars gesture and sat down at a long table.")
        print("you are surprised to see mr. Sharply. He was your former colleague and you had some tensions while you were working at the same job. You always argued about who got the nice hole puncher. You still have some tensions.")
    elif plus1 == "Mr. Sharply":
        print("he picks you up in a very polished, clean, snazzy 1950's looking car.")
        print("it starts raining very heavily on the way to the mansion. it is a 30 minute drive.")
        print("It's kind of awkward, you guys used to work at the same job but not anymore. You don't know what to say.")
        print("you are kinda like, really hungry and you have a pancake in the bag you packed.")
        eat_pancake = input("do you eat the pancake?   ")
        if eat_pancake == "yes":
            print("Mr. Sharply yells at you for getting crumbs in his car. He dumps you into the side of the road into the pouring rain.")
            print("he writes his phone number on a peacock feather that was in his car and says to venmo him money for a cleaner to do a deep clean because of the nastiness you developed during the time you were sitting there.")
            print("you get mad.")
            print("    ")
            print("but you must go to the party, because you said you would. ")
            print("you start crawling on the wet pavement to the mansion.")
            print("it would've been a 10 minute drive from where you were, but you were so defeated and walking so it was about an hour long to get to the mansion")
            print("       ")
            print("once you arive you are soaking and your clothes are dirty.")
            print("you ring the doorbell and someone opens the door.")
            print(f"''OH MY. {name}, whatever happened to you? Well, come in. I am Guntar'' the butler who opened the door said. You steped in and saw Mr. Sharply, his nose up and refusing to look at you.")
            print("''Mr. Sharply made me CRAWL IN THE RAIN.'' you answered glaring at Mr. Sharply. Guntar looks at you then Mr. Sharply.")
            print(f"''well, lets put the past in the past,'' guntar said.")
            print("''anyways, it has been a while we have been waiting for you,'' guntar glanced at Mr. Sharply.")
            print(" '' everyone has come here, as it has been about an hour. Let's start dinner, shall we?'' Guntar led you into the dining room where Mr. Sharply sat down and around the table was Miss Peacoat, Nessy Lock, Charles William the senator, and Zepper.")
            print(" *i wonder why Zepper is here* you think. Zepper is known for being really shady and doing shady things.")
        if eat_pancake == "no":
            print("you drive for about 10 more minutes. during that 10 minutes you get even more absurdly hungry and your stomach growls a lot very loudly.")
            print("Mr. Sharply looks at you with disgust and says you are distrubing his car with your stomach. You apologize and you don't talk again the whole time you are going to the mansion.")
            print("     ")
            print("    ")
            print("you get the feeling Mr. Sharply doesn't really like you.")
            print("you arrive at mansion")
            print(f" ''hello and welcome, {name} and Mr. Sharply'' the butler said. ")
            print(" ''my name is Guntar'' the butler, Guntar said. ")
            print(" ''please, let me take your jackets,'' he said")
            print("you and Mr. Sharply hand over your soaking wet jackets. they got so wet from the time you ran from the car to the door. You and Mr. Sharply stepped into the warm and fancy mansion.")
            print(" ''this is a very nice place you have,'' you said.")
            print(f" ''why thank you, {name}, not mine though,'' Guntar called over his shoulder while he led you and Mr. Sharply to the main room. ")
            eztra = input(" at the same time, the doorbell rings, and Guntar the butler opens the door again.")
            print("  ")
            print("  ")
            print("--------------------------------------------------")
            print("The door opens to reveal Mr. Sharply, Miss Peacoat, Charles William the senator, and Zepper.")
            print("''why is Zepper here?'' you hear someone whisper. Zepper is known for doing a bunch of shady things.")
            print("You, Nessy Lock, Mr. Sharply, Charles, Zepper, and Miss Peacoat all walked into the dining room at Guntars gesture and sat down at a long table.")
        else:
            print("------------------")
            print("you die of hunger. like, just answer yes or no it's not that hard.")
    elif plus1 == "Nessy Lock":
        print("nessy arrives are your door.")
        print(f"''Hi {name}! I am soooo excited to go to the partyy!!!")
        print("you look at Nessy. She has college-party clothes on. You had put on your nicest clothes")
        print("''you DO know this is a fancy dinner party at an old mansion.. right?'' you ask")
        print("She looks at you for a while, not saying anything.")
        print("''of course i knewwwww... you don't have any spare clothes, do you?'' nessy asks")
        print(" you sigh.")
        print(" '' the only thing i have is my moms old wedding dress. she passed away three years ago.'' you say.")
        print(" ''PLEAAASEEEE'' nessy says''")
        print("'' fine but you cannot let ANYTHING happen to it!'' you say")
        print("'' i promise!!!'' nessy promises. you are skeptical, but want Nessy to be representable so you let her borrow it.")
        print("     ")
        print(" you drive to the mansion and happily talk the whole time there.")
        extraaa = input("you arrive at the mansion")
        print("  ")
        print("  ")
        print(f" ''hello and welcome, {name} and Nessy Lock'' the butler said. ")
        print(" ''my name is Guntar'' the butler, Guntar said. ")
        print(" ''please, let me take your jackets,'' he said")
        print("you and Nessy hand over your soaking wet jackets. they got so wet from the time you ran from the car to the door. You and Nessy stepped into the warm and fancy mansion.")
        print(" ''this is a very nice place you have,'' you said.")
        print(f" ''why thank you, {name}, not mine though,'' Guntar called over his shoulder while he led you and Nessy to the main room. ")
        eztra = input(" at the same time, the doorbell rings, and Guntar the butler opens the door again.")
        print("   ")
        print("  ")
        print("The door opens to reveal Mr. Sharply, Miss Peacoat, Charles William the senator, and Zepper.")
        print("''why is Zepper here?'' nessy whispers in your ear. Zepper is known for doing a bunch of shady things.")
        print("You, Nessy Lock, Mr. Sharply, Charles, Zepper, and Miss Peacoat all walked into the dining room at Guntars gesture and sat down at a long table.")
        print("you are surprised to see mr. Sharply. He was your former colleague and you had some tensions while you were working at the same job. You always argued about who got the nice hole puncher. You still have some tensions.")
        eztrra = input("everyone takes a seat at the table")
        print("------------------------------")
        print("''I am guessing you guys are all wondering about why you all are gathered here. Yes, this is a very random selection. You are probably wondering what you all have in common,'' Guntar starts speaking, ''this invite is presented to you by... the only, Mr. Pebbler.'' ")
        print("             ")
        print("  ")
        print("you hear gasps. this is kind of random. Pebbler was your old boss at the same job that you worked at with Mr. Sharply.")
        print("What could Pebbler want, and where was he? Why wasn't he here? And what did the other people have in relation to Pebbler?")
        print("    ")
        print("And especially Zepper. Why would Pebbler invite him, out of all people?")
        print("   ")
        print("why would Pebbler invite this odd combination of guests to a fancy dinner party at an old mansion?")
        print("Soon, the food came and everyone started eating and having some nice conversations. Everyone still wondering where Pebbler was and why they were here, but quickly were distracted by the free fancy food.")
        print("   ")
        print(" you talk to Nessy. She is trying to find a job, since she is fresh out of university. Miss Peacoat has started a tailoring company on Greenshire Ave, and you promise to stop by if you need to hem something. You try to make some nice small talk with Mr. Sharply, but he clearly isn't interested in even interacting. No one is brave enough to talk to Zepper. Only a quick 'hello, how are you' and everyone turns away.")
        print("  ")
        okakkd = input("Guntar taps on a glass. Everyone turns.")
        print("     ")
        print("-------------------------------------------------")
        print(f"''Alright everyone,'' he says, ''everyone has had a turn to talk to one another. But for the most of formal introductions, let's all say aloud how we know kind sir Mr. Pebbler. {name}, would you like to go first?'' Guntar looks at you ")
        print("''Okay, alright. I knew Pebbler since he was my old boss.'' you say.")
        print(" Mr Sharply clears his throat.")
        print(f"'' same here,'' he says, ''me and {name} used to be co-workers and Pebbler was out boss.'' ")
        print("''I'll go next,'' Nessy says, ''I knew him through univesity, he used to be a proffesor and he was mine. We weren't like, close. So I don't really know why I am here.''")
        print("  ")
        print("''Me? MOI? Well, of course I will talk,'' Charles Williams chuckled and straightens his suit, ''Obviously I know Zepper through politics. What else?'' he snorted.")
        print("''I suppose I am next,'' Miss Peacoat clears her throat. ''me and Pebbler used to see eachother,'' she carefully worded, ''but many moons ago. Same as dear Nessy Lock, I have no thought in the world why I am here today. But I suppose no one does,'' she finished. ")
        print(" ")
        print("only Zepper is left.")
        print(" '' Hi guys. I am Zepper. I guess you know that though, judging off no one talking to me.'' he says. You feel bad all of sudden, he must feel lonely.")
        print("''yeah, well, I am also surprised why I am here. It's random but I guess not that random, since...''")
        print(" ")
        adadfaafdaf = input("'' since...'' Zepper said again.")
        print("   ")
        print("  ")
        print("  ")
        print("''since Pebbler is my brother.'' Zepper finally said.")
        print("___________________________________________________________________________________________")
        afdfakd = input("everyone is very surprised.")
        print("   ")
        print("----------------")
        print("soon everyone is warmed up to Zepper, not very close but at least are able to talk to him. ")
        print(" ")
        print("turns out, he is a very chill guy and the only shady thing he did was smoke once in highscool. He told everyone that the reason all people think he is shady is because he always lived in Pebblers shadow as a child and became accustomed to just being there and being shallow and lurking. Therefore, people assumed he was unstable and a bad person.")
        print("  ")
        print("everyone felt very sorry for Zepper. except for Mr. Sharply. He probably did feel bad, he just doesn't show emotions.")
        print("   ")
        input("everyone is still wondering where Pebbler is.")
        print("------------------------------")
        print("  ")
        input("Suddenly, the lights go out.")
        print("-----------")
        print("   ")
        print("you hear glass shatter and a scream that was cut off")
        input("it's silent for a moment.")
        print("suddenly the lights turn back on.")
        input("you see glass on the floor and the white tablecloth had deep red spots on it")
        print("---------")
        print(" you turn around to see Charles Williams, lying on the floor, unmoving.")
        
    else:
        print("you have to go with someone. you can't go alone. restart.")
else:
    print("you HAVE to go to the party. restart the program.")
    