print("welcome to this falled theme mad libs where you will visit the pumpkin patch with SNOOPY")
answer_for_snoopy = input("Do u like snoopy? ")
if answer_for_snoopy == "yes":
    print("yay snoopy is the best!")
else:
    print("oh.")
    print("ur pretty weird")
    print("well its too bad if u don't like snoopy becuase ur going to the pumpkin patch with him so i guess that sucks for you")
print("okay anyways lets start yes,")
name = input("also what is ur name ")
print(f"okay {name}, we are now going to starttt")
adjective1 = input("give me an adjective ")
pluralnoun2 = input("okay now i need a plural noun ")
adjective2 = input("another adjective ")
pluralnoun1 = input("now a plural noun ")
noun2 = input("a noun! ")
adjective3 = input("another adjective! ")
food = input("okay now give me a super super super yummy fall/autumn food! ")
adjective4 = input("okay another adjective ik your probably sick of these but...yeah idk just give me an adjective ")
adverb = input("okay now an adverb!! ")
adjective5 = input("okay now this is the last one ! i need an adjective.. again sorry but last one! ")
print("okay. we are now ready to tell the story of {name} and snoopy at the pumpkin patch")
print("____________________________________________________")
print("____________________________________________________")
print(f"It was a {adjective1} fall afternoon and the {pluralnoun2} were falling. They are so colorful and {name} put on a cute fall sweater and stepped")
print("outside to meet snoopy!")
print(f"snoopy is very {adjective2} to see {name}. {name} and snoopy walk over to the pumpkin patch and snoopy tells {name} about the great")
print(f"pumpkin, who scares the {pluralnoun1} out of the children every halloween!")
print(f"{name} and snoopy go looking for the biggest pumpkin, and a couple minutes later, {name} sees Snoopy and he has found a pumpkin")
print(f"the size of a {noun2}.")
print(f"'wow that is absolutely {adjective3}!!' {name} exclaimed")
print(f"snoopy and {name} went to go get hot apple cider and {food}. After eating and drinking, snoopy and {name} went over to the corn maze")
print(f"'this corn is so {adjective4}' {name} said.")
print(f"they went through twists and turns and came out of the corn maze very quickly. Experts at the maze.")
print(f"'WOw, we did that so {adverb}!' snoopy barked.")
print(f"it was getting very {adjective5} so {name} and snoopy went home and started carving their pumpkinsthat they picked out at the patch.")
print("thats the end!")
print("thank you for visiting the pumpkin patch with snoopy!")